export const dataCustomer = [
  //   { rowLength: 5 },
  {
    id: 1,
    name: "Odis Rhinehart",
    level: "Warga",
    menu: "Chicken & Ribs Combo",
    IDR: 194700,
    detail: "Detail",
  },
  {
    id: 2,
    name: "Kris Roher",
    level: "Warga",
    menu: "Surf & Turf Basket",
    IDR: 631200,
    detail: "Detail",
  },
  {
    id: 3,
    name: "Serenity Fisher",
    level: "Juragan",
    menu: "Fried Chicken Dinne",
    IDR: 1040920,
    detail: "Detail",
  },
  {
    id: 4,
    name: "Broklyn Warren",
    level: "Sultan",
    menu: "Surf & Turf Gift Basket",
    IDR: 730500,
    detail: "Detail",
  },
  {
    id: 5,
    name: "Franco Delort",
    level: "Juragan",
    menu: "Chicken & Ribs Combo",
    IDR: 96000,
    detail: "Detail",
  },
  {
    id: 6,
    name: "Saul Geoghegan",
    level: "Juragan",
    menu: "Surf & Turf Gift Basket",
    IDR: 256000,
    detail: "Detail",
  },
  {
    id: 7,
    name: "Alfred Vetros",
    level: "Juragan",
    menu: "Dark & Stromy",
    IDR: 590080,
    detail: "Detail",
  },
  {
    id: 8,
    name: "Cristofer Vetros",
    level: "Konglomerat",
    menu: "Shaking Beef Tri+ Tip",
    IDR: 782600,
    detail: "Detail",
  },
  {
    id: 9,
    name: "Calvin Steward",
    level: "Konglomerat",
    menu: "BBQ Rib Dinner",
    IDR: 467500,
    detail: "Detail",
  },
  {
    id: 10,
    name: "Calvin Steward",
    level: "Konglomerat",
    menu: "BBQ Rib Dinner",
    IDR: 467500,
    detail: "Detail",
  },
];
export const columns = [
  {
    field: "name",
    headerName: "Customer Name",
    width: 200,
  },
  {
    field: "level",
    headerName: "Level",
    width: 200,
  },
  {
    field: "menu",
    headerName: "Favorite Menu",
    width: 250,
  },
  {
    field: "IDR",
    headerName: "Total Transaction",
    width: 200,
  },
  {
    field: "detail",
    headerName: " Action",
    width: 200,
  },
];
